[package]
name = "geo-driver"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
geo-backend = { path = "../geo_backend" }
geo-codegen = { path = "../geo_codegen" }
geo-diagnostics = { path = "../geo_diagnostics" }
geo-semantic = { path = "../geo_semantic" }
geo-source = { path = "../geo_source" }
